### ISSUE TITLE
person attribute

### ISSUE THREAD

**Issue by eeric** [Zplusdragon/PLIP#11]
The pretrained model needs to pass in tokens and masks to generate attribute descriptions. It seems that there is no way to generate pedestrian attribute descriptions just by inputting images.

**Comment by Zplusdragon** [comment]
Attribute descriptions? What do you mean? You mean SPAC？ SPAC is a captioner (not a pretrained model) we trained to generate complete textual descriptions and six attribute descriptions by inputting images. We will make it publicly available after this paper is accepted.

**Comment by eeric** [comment]
how to output complete textual descriptions and six attribute descriptions?
