### ISSUE TITLE
python zs_inference.py 运行出错

### ISSUE THREAD

**Issue by Flzjler** [Zplusdragon/PLIP#15]
您好，我在执行```python zs_infer.py```命令后出现如下错误：
```
RuntimeError: Error(s) in loading state_dict for Textual_encoder:
        Unexpected key(s) in state_dict: "encoder.embeddings.position_ids".
``` 

定位到的错误代码在```zs_infer.py```文件的```Test_main()```函数中。
执行代码下面代码时出现错误：
```model.text_encoder.load_state_dict(checkpoint["TxtEncoder_state_dict"])```

是给定的checkpoints文件有问题，还是hugging face下载下来的模型有问题。
能否提供您的```bert-base-uncased```文件，默认路径应该在```~/.cache/huggingface/hub/models--bert-base-uncased/```

**Comment by Zplusdragon** [comment]
是bert的版本不一致的原因，你将代码改成 model.text_encoder.load_state_dict(checkpoint["TxtEncoder_state_dict"],strict=False) 就可以了，不影响结果。

**Comment by Zsj-bv** [comment]
> 是bert的版本不一致的原因，你将代码改成 model.text_encoder.load_state_dict(checkpoint["TxtEncoder_state_dict"],strict=False) 就可以了，不影响结果。

解决了，非常感谢。
