### ISSUE TITLE
Can you provide downstream task for Image based ReID?

### ISSUE THREAD

**Issue by Realdr4g0n** [Zplusdragon/PLIP#4]
Hello, I am very interested in your research. Thanks for sharing your good research results

I'm researching Person Re-ID, and I saw the results in the paper listing few shot training from 0% (I understood it as zero-shot, is that correct?) to 90% in Table 6. If you don't mind, could you share some experimental code that runs this downstream task?

**Comment by Zplusdragon** [comment]
According to the plan, we will share the code of all the downstream tasks after this paper is accepted. If you need the code of the few-shot setting, you can turn to the official LUP repo for the training details.

**Comment by Realdr4g0n** [comment]
Okay, Thx!
