### ISSUE TITLE
Question about SPAC code and training data

### ISSUE THREAD

**Issue by hh23333** [Zplusdragon/PLIP#6]
Hello, I am very interested in your work and I have some questions:

1. Will you release the code for the part of SPAC?
2. How did you obtain the attribute annotations for the training data of SPAC?

Thank you for your time and attention. I look forward to hearing from you soon.

**Comment by Zplusdragon** [comment]
I will release the inference code of SPAC after this paper is accepted. The question about the attribute annotations can be found in #1
