### ISSUE TITLE
runtime error when Fine-tuning 

### ISSUE THREAD

**Issue by tianxingyzxq** [Zplusdragon/PLIP#8]
when I run fine-tuning command CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 train.py, then get runtime error:
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Text_encoder:
Unexpected key(s) in state_dict: "encoder.embeddings.position_ids".
my transformer version is 4.32.0

**Comment by Zplusdragon** [comment]
My transformer version is 4.26.1. The error may be due to the update of the bert model in transformer. You can try to keep your transformer version in line with mine.

**Comment by YoungGenuineLee** [comment]
In my case, using pretrained weight released in README, transformers version is 4.31 and little code change in "train.py"

`checkpoint = torch.load(model_file)
### What I added ###
    checkpoint['TxtEncoder_state_dict'].pop("encoder.embeddings.position_ids")
#################
    model.image_encoder.load_state_dict(checkpoint["ImgEncoder_state_dict"])
    model.text_encoder.load_state_dict(checkpoint["TxtEncoder_state_dict"])`

**Comment by tianxingyzxq** [comment]
Okay, Thx!
